hash-format = "sha256"

[[files]]
file = "mods/architectury-api.pw.toml"
hash = "1f450b1df03f577fb2d34745cf43dca40553b17973c0e90fd2b30712e71e6ca9"
metafile = true

[[files]]
file = "mods/catharsis.pw.toml"
hash = "750ffdcb97cf88724db9eb61723efecd0a14475c56bd568a631831420fb22826"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "bbf28818ac59c19583f03d516a86b508e7da7a591c28d071c4e53effd4865bf6"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
hash = "ca2147ccc6cd2a9d8ee484dd796ae8e1c5de42551c9366f2d09915bbe1c0002e"
metafile = true

[[files]]
file = "mods/fabric-language-kotlin.pw.toml"
hash = "344ca02ae26f79bc11dc6d65751503613964da6761fcda5a33291dc7d8aae36f"
metafile = true

[[files]]
file = "mods/firmament.pw.toml"
hash = "e2b141843d658823f6861bd795f09ba60410a6a3c51a7f99c69a5c29910b4c2b"
metafile = true

[[files]]
file = "mods/hsm.pw.toml"
hash = "459a5515e9246e361e61d8b3b6fb2ffda11cdd34077270fe728599dbc589631d"
metafile = true

[[files]]
file = "mods/hypixel-mod-api.pw.toml"
hash = "23fb78f56ab631dcb4f249b64feb03293f1f44e39ea65b3eba7dcd37d74be005"
metafile = true

[[files]]
file = "mods/modern-warp-menu.pw.toml"
hash = "86669467353a4b1db9df5ba18baf99afd9d56faded54d29db74393134b8deae2"
metafile = true

[[files]]
file = "mods/rei.pw.toml"
hash = "bf2c053158e6eb1c471160c47328615a2c62f7b358886793b6fda97d7e9d351f"
metafile = true

[[files]]
file = "mods/skyblock-custom-scoreboard.pw.toml"
hash = "e8bcd345ba7f66ae7682a811ea0f5d76f8ccb97639470a3edd4d380b0426493f"
metafile = true

[[files]]
file = "mods/skyblock-profile-viewer.pw.toml"
hash = "aaf7935aeb9b3227e9873718bb180b6ec7cb94784c9a3ca759b89bdfeeb7fb77"
metafile = true

[[files]]
file = "mods/skyblock-rpc.pw.toml"
hash = "95f16dd4275e96ed7db62db4083b0cadbf7a5b9644725b57a2edbcd488be9312"
metafile = true

[[files]]
file = "mods/skyblocker-liap.pw.toml"
hash = "fa6656d12a4e606373db04287e79b47d70d0437ad3589aa16c865e48abe7a7bd"
metafile = true

[[files]]
file = "mods/skycubed.pw.toml"
hash = "bace82d3e60fbb3630eac4f9efc536808d162cdf91463e1ea0c710dd593bcd38"
metafile = true

[[files]]
file = "mods/skyhanni.pw.toml"
hash = "5ed616dc20412f88381bb0ba8a77290786cf67c77be142f0220b1de69da54808"
metafile = true

[[files]]
file = "mods/skyocean.pw.toml"
hash = "3dd420a28a38127ceed0480ca0d8caca9dcc24d34d18ea4cb9034c6c19650a9e"
metafile = true

[[files]]
file = "mods/yacl.pw.toml"
hash = "1765c84b093eba73f278a6f7af45f722445f35f08f8f9c103e6df42c28446f8e"
metafile = true

[[files]]
file = "resourcepacks/bazaar-graph-fix.pw.toml"
hash = "feb3a290dd748fadbb77c5a4c1a53e3ea799c964e8d0cc31420d5a9070516333"
metafile = true

[[files]]
file = "resourcepacks/darkmodeskyblock.pw.toml"
hash = "9a7855ffdce0933f0a83d547bf1cbe15ba245873aab38107378f56868a911e79"
metafile = true

[[files]]
file = "resourcepacks/furfsky-reborn.pw.toml"
hash = "60a8528fd3f4debf440a952381c889bf4fa695877667646c74d06a58753b8171"
metafile = true

[[files]]
file = "resourcepacks/skyblock-dark-ui.pw.toml"
hash = "8d97dfe63cbd6819d3b1aad38ec8ff89f2ac89a389f4f92cd835ba6f083537d0"
metafile = true
