hash-format = "sha256"

[[files]]
file = "mods/architectury-api.pw.toml"
hash = "dbc4960d91ef836961171d8a13f8adc29ee6df2c63ea23efeca96fc93e5d280a"
metafile = true

[[files]]
file = "mods/catharsis.pw.toml"
hash = "83bbf85d47ce03c48dbd077647b3019c73f0cb53e4ee3e393da12f3d7bb7c242"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "9c22bad4f0d606f92ce105da00204c29aa2b356401cc5d1088f63bb02f90d351"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
hash = "71057ffacb79edc48ef50b33ba506255e3da4ad48e8d0eaa4635368097567ba9"
metafile = true

[[files]]
file = "mods/fabric-language-kotlin.pw.toml"
hash = "344ca02ae26f79bc11dc6d65751503613964da6761fcda5a33291dc7d8aae36f"
metafile = true

[[files]]
file = "mods/firmament.pw.toml"
hash = "e8a0d012c303fad97a4fd77b115acb82e037a054fb445c5b38e90877892634f0"
metafile = true

[[files]]
file = "mods/hsm.pw.toml"
hash = "459a5515e9246e361e61d8b3b6fb2ffda11cdd34077270fe728599dbc589631d"
metafile = true

[[files]]
file = "mods/hypixel-mod-api.pw.toml"
hash = "23fb78f56ab631dcb4f249b64feb03293f1f44e39ea65b3eba7dcd37d74be005"
metafile = true

[[files]]
file = "mods/modern-warp-menu.pw.toml"
hash = "4e6e3d8ead7ad1a786d874e634ef263d1be96ba3c29fa40f2d166d1252f18b46"
metafile = true

[[files]]
file = "mods/modmenu.pw.toml"
hash = "94828f99c4d81ae74fdc9daa04a45bb1bdc030d89140f265c323e9f9d03f2d9e"
metafile = true

[[files]]
file = "mods/rei-search-bar-calculations.pw.toml"
hash = "cf8639db0c326fe1d1c691c711fb79e0bc9f841d49259e14b68422e88f5d35bd"
metafile = true

[[files]]
file = "mods/rei.pw.toml"
hash = "48902aca1d72f5fbbe0b967f5e91618e80d0c105e7f5ec5a88c78dbc492c60be"
metafile = true

[[files]]
file = "mods/skyblock-custom-scoreboard.pw.toml"
hash = "db2ae2560ac50c5310b05812419119a771baa9035bac8ed8d04b5f3089d7743a"
metafile = true

[[files]]
file = "mods/skyblock-profile-viewer.pw.toml"
hash = "5965df3b6ac028c36bfbb9336997dad96b9df446a7a69f677f02a529eb51c4a3"
metafile = true

[[files]]
file = "mods/skyblock-rpc.pw.toml"
hash = "95f16dd4275e96ed7db62db4083b0cadbf7a5b9644725b57a2edbcd488be9312"
metafile = true

[[files]]
file = "mods/skyblocker-liap.pw.toml"
hash = "7b074655d662097e78cf0712f8339c45e1418c666d37073cb398cbc0c823f77b"
metafile = true

[[files]]
file = "mods/skycubed.pw.toml"
hash = "240dde9e6ef45422d8e6a6b415690e2638e15964417e811fa99491a81b758a23"
metafile = true

[[files]]
file = "mods/skyhanni.pw.toml"
hash = "84a3bbd2a1d54cbd62530310ee45afee437fe654ccc7544b136aa18350c33bf7"
metafile = true

[[files]]
file = "mods/skyocean.pw.toml"
hash = "f4029a18560d259d44825be5c696584d71cc7848ae76471c676a80f1da7da511"
metafile = true

[[files]]
file = "mods/yacl.pw.toml"
hash = "e3208008761017ce98dabe50c37fad65f56ece476d6b678b7d1eb9eab39bc1a1"
metafile = true

[[files]]
file = "resourcepacks/bazaar-graph-fix.pw.toml"
hash = "feb3a290dd748fadbb77c5a4c1a53e3ea799c964e8d0cc31420d5a9070516333"
metafile = true

[[files]]
file = "resourcepacks/dark-mode-skyblock.pw.toml"
hash = "1888dcb3e8d7102f92447df7c6b54ed5156de590c5ee0a8c359d96109c379e19"
metafile = true

[[files]]
file = "resourcepacks/furfsky-reborn.pw.toml"
hash = "60a8528fd3f4debf440a952381c889bf4fa695877667646c74d06a58753b8171"
metafile = true

[[files]]
file = "resourcepacks/hypixel-plus.pw.toml"
hash = "9b6427a062f756899e340705a0e7b4ecf0c36c8c4ab833b6bb67ffd6b24be581"
metafile = true

[[files]]
file = "resourcepacks/skyblock-dark-ui.pw.toml"
hash = "8d97dfe63cbd6819d3b1aad38ec8ff89f2ac89a389f4f92cd835ba6f083537d0"
metafile = true
