name = "OneClient 1.21.10 Fabric [SkyBlock]"
author = "Polyfrost"
version = "1.0.0"
pack-format = "packwiz:1.1.0"
poly-format = "1"
enabled = false
category = "SkyBlock"
id = "skyblock-1.21.10-fabric"
update-url = "oneclient/generated/skyblock-1.21.10-fabric.mrpack"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "edf0d047b189463d4b6b75ff47f1f03b7ef6361355fd3a55d427a2d8a2328f9c"

[versions]
fabric = "0.18.4"
minecraft = "1.21.10"
