name = "OneClient 1.21.10 Fabric [SkyBlock]"
author = "Polyfrost"
version = "1.0.0"
pack-format = "packwiz:1.1.0"
poly-format = "1"
enabled = false
category = "SkyBlock"
id = "skyblock-1.21.10-fabric"
update-url = "oneclient/generated/skyblock-1.21.10-fabric.mrpack"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6e96f8ff5d20b3af8ae1d378ef20b3ce502d1fb8d944edbec2daa79522813131"

[versions]
fabric = "0.18.4"
minecraft = "1.21.10"
