hash-format = "sha256"

[[files]]
file = "mods/animatium.pw.toml"
hash = "f0d0b41c6d816149e906e693506f12280cdd42ac31112abb5b7ad38e1a758927"
metafile = true

[[files]]
file = "mods/architectury-api.pw.toml"
hash = "1f450b1df03f577fb2d34745cf43dca40553b17973c0e90fd2b30712e71e6ca9"
metafile = true

[[files]]
file = "mods/better-stats.pw.toml"
hash = "3a74dc44e1f121945e3eebf4e346ebe941f09458f36024f5826f779cca2ac498"
metafile = true

[[files]]
file = "mods/bettercommandblockui.pw.toml"
hash = "c372db12962c08d4e319bb91416478a62fe2320373fb24b2152ab7585b895bb0"
metafile = true

[[files]]
file = "mods/betternightvision.pw.toml"
hash = "a80e53a334ee3bd4c2ac4f06cf156a7843c91953e3724d7b0a64484010c68c1d"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "bbf28818ac59c19583f03d516a86b508e7da7a591c28d071c4e53effd4865bf6"
metafile = true

[[files]]
file = "mods/commandkeys.pw.toml"
hash = "d6ea9ed22f6b1361405215c7a79ab4187ae800d150b2c07da354572cb603f105"
metafile = true

[[files]]
file = "mods/controlify.pw.toml"
hash = "96883dbb19db2b62f6b64750f34f92717509ac6bf08159c8dcb8b16e618fca46"
metafile = true

[[files]]
file = "mods/crash-assistant.pw.toml"
hash = "4a77c4c057c6344ab1479c87dd9405007d96a416c04701c493eb6f9d602dff93"
metafile = true

[[files]]
file = "mods/euphoria-patches.pw.toml"
hash = "e918132ab17f31eacc1a055d54bba6ee59a208a5f43af7a89730b39698968ec7"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
hash = "ca2147ccc6cd2a9d8ee484dd796ae8e1c5de42551c9366f2d09915bbe1c0002e"
metafile = true

[[files]]
file = "mods/fabric-language-kotlin.pw.toml"
hash = "344ca02ae26f79bc11dc6d65751503613964da6761fcda5a33291dc7d8aae36f"
metafile = true

[[files]]
file = "mods/frozenlib.pw.toml"
hash = "fdd88c9c1f4574ad0c81c8d257ab551afaa63b894db843b02d4dfad86afae869"
metafile = true

[[files]]
file = "mods/gamma-utils.pw.toml"
hash = "f257a9011255f3ae03f9bd9483e8152ebf7dbae220ab3c6f26cd0b7ee1279bd2"
metafile = true

[[files]]
file = "mods/hypixelautogg.pw.toml"
hash = "d3b089f13d6018ddf3af0be6ddf238279a64270e94bf46deeafe44fd0db13792"
metafile = true

[[files]]
file = "mods/in-game-account-switcher.pw.toml"
hash = "719cb7f719f8c4c672e5c83779d06b8091901525848899796f0558f4a0a4aad6"
metafile = true

[[files]]
file = "mods/jade.pw.toml"
hash = "7788df4221c4004f85a81e3e9779b8edf49ad83a3506c3451fff1f9ff6ba985d"
metafile = true

[[files]]
file = "mods/libjf.pw.toml"
hash = "34304d5974a9f821336c536fad8b92ac6c79eac96560f7176bdeda6404d540db"
metafile = true

[[files]]
file = "mods/modmenu.pw.toml"
hash = "3813a732444fe1b477eadf4d1b8a2e420bd9a74cc3285037da624b27884a029e"
metafile = true

[[files]]
file = "mods/notenoughcrashes.pw.toml"
hash = "e3c50f87924030ad0bb72361da9d7861a9d5acd98cf96db51a89410d60ff9274"
metafile = true

[[files]]
file = "mods/noxesium.pw.toml"
hash = "3d22391d697b39f61a5844e236a8e911d5404e076d457438972d77335d63f665"
metafile = true

[[files]]
file = "mods/quickjoin.pw.toml"
hash = "83f33a07c5875a2b0c0f5c73bf0f5b173e3bf3f766801e7f0eb0a1762ed7b099"
metafile = true

[[files]]
file = "mods/resourcify.pw.toml"
hash = "e3f496557717706ec054cb82c2407d1ed69cce3dea69f57620f9771558d753d1"
metafile = true

[[files]]
file = "mods/respackopts.pw.toml"
hash = "6174f38823e40f620b7cc1eb823564c1b3350358737b06dce78001b2e91fd290"
metafile = true

[[files]]
file = "mods/rsls.pw.toml"
hash = "c3356166d08f306c98ef527b09656face36da3f10c908dbb8879d15f47532562"
metafile = true

[[files]]
file = "mods/shulkerboxtooltip.pw.toml"
hash = "60aa723f81138dc7bbe81071ec7e0c4260aeb90b513ab9edbdc4396b83ba825d"
metafile = true

[[files]]
file = "mods/simple-block-overlay.pw.toml"
hash = "e925f2101d1f66b2d1d569053dccb7e23d8c75b6725365d9c4fdf2a68ffa6a17"
metafile = true

[[files]]
file = "mods/simple-voice-chat.pw.toml"
hash = "b2a0747daded249a1b9805356cd5f5bb823f83a3a7bbd2cf2828dfd754157af4"
metafile = true

[[files]]
file = "mods/sound-controller.pw.toml"
hash = "d068f9268e33feff7a4e790c7f503ab67d5d27a21d1e9eb37f10ec71db489204"
metafile = true

[[files]]
file = "mods/spark.pw.toml"
hash = "364d8523babd43355024dc79a88bc41740d0c091ded2c04f07ba1a2150091898"
metafile = true

[[files]]
file = "mods/stackdeobf.pw.toml"
hash = "f2908d9033570d993a21f671304f08edb7696d65260b58e2b55d0c943f9b172c"
metafile = true

[[files]]
file = "mods/tcdcommons.pw.toml"
hash = "2de7556d2d0a5cd1cc2b9215f581c3dc7e05205e29038484180bfac23efd217e"
metafile = true

[[files]]
file = "mods/toggle-toggle-sprint.pw.toml"
hash = "c8f603f98338f7e5e2844d6b5375491d8d0abbf99fe1c0ff952d1530cc44e5c2"
metafile = true

[[files]]
file = "mods/viafabricplus.pw.toml"
hash = "25491e2a269db1933b64903b163aec98603dff0e43a428bd720c036480014982"
metafile = true

[[files]]
file = "mods/yacl.pw.toml"
hash = "1765c84b093eba73f278a6f7af45f722445f35f08f8f9c103e6df42c28446f8e"
metafile = true

[[files]]
file = "mods/zoomify.pw.toml"
hash = "a00b3c7112e2736071c7c1de8d345073f7b80dbd7ef056b183b25c9ac46822eb"
metafile = true
