name = "OneClient 1.21.11 Fabric [Utility]"
author = "Polyfrost"
version = "1.0.0"
pack-format = "packwiz:1.1.0"
poly-format = "1"
enabled = true
category = "Utility"
id = "utility-1.21.11-fabric"
update-url = "oneclient/generated/utility-1.21.11-fabric.mrpack"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "638740cc2eb6cea4db484b13578bbdb76253258897e20a5966a0d5c0ddb2a52d"

[versions]
fabric = "0.18.4"
minecraft = "1.21.11"
